/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as DownsellIntelligenceRouteImport } from './routes/downsell.intelligence'
import { Route as UpsellIntelligenceRouteImport } from './routes/upsell.intelligence'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const DownsellIntelligenceRoute = DownsellIntelligenceRouteImport.update({
  id: '/downsell/intelligence',
  path: '/downsell/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const UpsellIntelligenceRoute = UpsellIntelligenceRouteImport.update({
  id: '/upsell/intelligence',
  path: '/upsell/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/downsell/intelligence': typeof DownsellIntelligenceRoute
  '/upsell/intelligence': typeof UpsellIntelligenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/downsell/intelligence': typeof DownsellIntelligenceRoute
  '/upsell/intelligence': typeof UpsellIntelligenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/downsell/intelligence': typeof DownsellIntelligenceRoute
  '/upsell/intelligence': typeof UpsellIntelligenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/community' | '/downsell/intelligence' | '/upsell/intelligence'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/community' | '/downsell/intelligence' | '/upsell/intelligence'
  id:
    | '__root__'
    | '/'
    | '/community'
    | '/downsell/intelligence'
    | '/upsell/intelligence'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityRoute: typeof CommunityRoute
  DownsellIntelligenceRoute: typeof DownsellIntelligenceRoute
  UpsellIntelligenceRoute: typeof UpsellIntelligenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downsell/intelligence': {
      id: '/downsell/intelligence'
      path: '/downsell/intelligence'
      fullPath: '/downsell/intelligence'
      preLoaderRoute: typeof DownsellIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upsell/intelligence': {
      id: '/upsell/intelligence'
      path: '/upsell/intelligence'
      fullPath: '/upsell/intelligence'
      preLoaderRoute: typeof UpsellIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityRoute: CommunityRoute,
  DownsellIntelligenceRoute: DownsellIntelligenceRoute,
  UpsellIntelligenceRoute: UpsellIntelligenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
